### ISSUE TITLE
send feedback on scope and charter template

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/open-data-sprints#11]
@cityofaustin/odi-core-team 

by COB Thursday, 25 Aug if you can 

if you don't have any feedback, would y'all  mind sending me a little comment so I know not to follow up with you? thx! -hailey

**Comment by happinessk** [comment]
@haileypate the Scope and Charter looks good.

**Comment by whitlocka** [comment]
@haileypate - one typo in the scope.  Success is missing a s.  

Besides that all was good.

**Comment by haileypate** [comment]
thanks @whitlocka, i fixed the typo when i updated all the templates in #19 =)

**Comment by haileypate** [comment]
@MarbennCayetano we talked a lot about this stuff on Friday afternoon... if you have any more feedback, feel free to holler =)

**Comment by MarbennCayetano** [comment]
The project is more of an "Open Data Products Evaluation" as we may be comparing and evaluating a few different products.  Will updating the URL path name accordingly have an affect on the main landing page?
