### ISSUE TITLE
send project team member lists to hailey

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/open-data-sprints#12]
or, if you're feeling adventurous, add them yourself here: https://airtable.com/tblPUqyY903uySGEn/viwVHsklKnkzTL4NY

- [x] hailey
- [x] brad
- [ ] marbenn
- [x] happiness
- [x] anne

**Comment by BradleyMcCarty** [comment]
My team members are updated.

**Comment by haileypate** [comment]
@BradleyMcCarty you're the bomb! i had fun watching your live updates on the airtable 😄

**Comment by whitlocka** [comment]
I think i have successfully added the PIR Pilot team members

**Comment by haileypate** [comment]
awesome!! thanks @whitlocka !!

**Comment by happinessk** [comment]
My team members are updated.
