### ISSUE TITLE
write scope and charter for marbenn's project

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/open-data-sprints#20]
for starters... @MarbennCayetano -- what would you like to name the project? 

let me know, and i will write up the steps to making the change so you know how it works =)

**Comment by MarbennCayetano** [comment]
Coolio.  "Open Data Products Evaluation" should work.

**Comment by haileypate** [comment]
great =) i'll make the changes to the architecture. 

Also, here's a link to a worksheet for developing content for your scope and charter:

https://docs.google.com/document/d/1gJtdHyhGCAExxVQ8O8hDZnJt9Png8qY3Hh-AEf-P0qg/edit?usp=sharing

**Comment by haileypate** [comment]
updated your project name! see #21

**Comment by MarbennCayetano** [comment]
Mega thanks!

**Comment by haileypate** [comment]
marbenn did this... yay!
