### ISSUE TITLE
PIR Pilot Team List

### ISSUE THREAD

**Issue by whitlocka** [cityofaustin/open-data-sprints#26]
@haileypate can you help me correct my project team list.  It is showing Happiness team members and not mine that I updated in AirTable.

Thank you in advance,
Anne

**Comment by haileypate** [comment]
yikes, still? Thought I fixed that! Okay, please stand by




On Thu, Sep 8, 2016 at 11:01 AM -0500, "whitlocka" <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #26<https://github.com/cityofaustin/open-data-sprints/issues/26> to @haileypate<https://github.com/haileypate>.

-

**Comment by haileypate** [comment]
okay, fixed by #27 , please let me know if i can provide anything further!
